#terraform {
#  required_providers {
#    local = {
#      source = "hashicorp/local"
#      version = "1.4.0"
#    }
#  }
#}

resource "local_file" "pet" {
  #filename = var.filename[count.index]
  #count = 3
  #count = length(var.filename)
  filename = each.value
  for_each = toset(var.filename)
  content = "My favorite pet is ${random_pet.my-pet.id}"
  #content = data.local_file.dog.content
  file_permission = "0700"

  lifecycle {
     #create_before_destroy = true
     #ignore_changes = all
     #prevent_destroy = true
  }
}

#data "local_file" "dog" {
#  filename = "/root/dog.txt"
#}

resource "random_pet" "my-pet" {
  prefix = var.prefix[0]
  separator = var.separator
  length = var.length
}

output "pet-name" {
  value = random_pet.my-pet.id
  description = "Record the value of pet ID generated by the random_pet resource"
}
