resource "local_file" "pet" {
  filename = var.filename
  content = "My favorite pet is ${random_pet.my-pet.id}"
  file_permission = "0700"

  lifecycle {
     #create_before_destroy = true
     #ignore_changes = all
     prevent_destroy = true
  }
}
resource "random_pet" "my-pet" {
  prefix = var.prefix[0]
  separator = var.separator
  length = var.length
}
output "pet-name" {
  value = random_pet.my-pet.id
  description = "Record the value of pet ID generated by the random_pet resource"
}
